# Generated by Django 5.0.3 on 2024-03-15 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hexagonapp', '0002_project_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_segments', models.TextField()),
                ('Value_proposition', models.TextField()),
                ('Channels', models.TextField()),
                ('Customer_relationships', models.TextField()),
                ('Revenue_streams', models.TextField()),
                ('Key_resources', models.TextField()),
                ('Key_activities', models.TextField()),
                ('Key_partners', models.TextField()),
                ('Cost_structure', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
