# Generated by Django 5.0.3 on 2024-03-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hexagonapp', '0003_project2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='industry_sector',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_market',
            field=models.TextField(max_length=100),
        ),
    ]
