# Generated by Django 5.0.3 on 2024-03-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hexagonapp', '0005_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='name',
            field=models.TextField(default='q'),
            preserve_default=False,
        ),
    ]
