# Generated by Django 5.0.3 on 2024-03-19 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hexagonapp', '0006_questions_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project2',
            old_name='Channels',
            new_name='channels',
        ),
        migrations.RenameField(
            model_name='project2',
            old_name='Cost_structure',
            new_name='cost_structure',
        ),
        migrations.RenameField(
            model_name='project2',
            old_name='Customer_relationships',
            new_name='customer_relationships',
        ),
        migrations.RenameField(
            model_name='project2',
            old_name='Customer_segments',
            new_name='customer_segments',
        ),
        migrations.RenameField(
            model_name='project2',
            old_name='Key_activities',
            new_name='key_activities',
        ),
        migrations.RenameField(
            model_name='project2',
            old_name='Key_partners',
            new_name='key_partners',
        ),
        migrations.RenameField(
            model_name='project2',
            old_name='Key_resources',
            new_name='key_resources',
        ),
        migrations.RenameField(
            model_name='project2',
            old_name='Revenue_streams',
            new_name='revenue_streams',
        ),
        migrations.RenameField(
            model_name='project2',
            old_name='Value_proposition',
            new_name='value_proposition',
        ),
    ]
